<?php
/**
 * @file
 */

/**
 * Implements hook_mail_alter().
 *
 * Mails with the 'X-Mail-Domain' header set won't be altered.
 *
 * The Return-Path will be set either way.
 *
 * For mails where all addresses in the "From" field are using the
 * site mail domain, the "From" field won't be changed. If the
 * "ReplyTo" field isn't set, the site "ReplyTo" address will be
 * set in the "ReplyTo" field.
 *
 * Mails where the domain of the address in the "From" field
 * doesn't match the site mail domain will be changed: the
 * "From" address will be changed into a "ReplyTo" address
 * and the site mail address will be set as new "From" address.
 *
 * @param $message
 */
function email_check_mail_alter(&$message) {
  // If X-Mail-Domain is set -> let the mail server do the "From" address
  // mangling.
  if (empty($message['headers']['X-Mail-Domain'])) {
    $site_mail_domain  = variable_get('site_mail_domain', NULL);
    $site_mail_address = variable_get('site_mail', NULL);
    $site_reply_to = variable_get('site_replyto_mail', variable_get('site_mail'));
    $site_return_path = variable_get('site_mail_return_path', variable_get('site_mail'));

    $site_mail_domain  = empty($site_mail_domain) ? 'campaignion.org' : $site_mail_domain;
    $site_mail_address = empty($site_mail_address) ? 'info@campaignion.org' : $site_mail_address;

    // make shure site_mail and site_mail_domain are consistend
    // make sure site_mail and site_mail_domain are consistend
    if (strpos($site_mail_address, '@' . $site_mail_domain) === FALSE) {
      $site_mail_address = 'info@' . $site_mail_domain;
    }

    // Deal with multiple header From addresses.
    //
    // Theoretically there could be more than 1 From address, e.g. if it was
    // set in the webform admin settings.
    //
    // We have the notion of the primary From address, i.e. the first address.
    // Only for this primary (first) From address we can enforce a DMARC
    // compliant email.
    $message_from_addresses = [];
    // When no address is found, no need to try sending the email.
    //
    // If an address is found, just deal with the first one to determine if
    // we need to set an Reply-To header.
    $pattern = '/(["][^"]+["])?[[:blank:]]*[<]?[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b[>]?/i';
    preg_match_all($pattern, $message['from'], $message_from_addresses);
    $message_from_addresses = array_shift($message_from_addresses); 
    $reply_to = !empty($message['headers']['Reply-To']) ? $message['headers']['Reply-To'] : '';
    foreach($message_from_addresses as $index => $address) {
      // Set a Reply-To if necessary.
      //
      // If the domain from the "From" address is not the site mail domain
      // we know we need to set a reply-to. So save the found address as
      // reply-to and use the site mail as From address (which we assume to be
      // valid).
      //
      // Only set the address as reply-to if reply-to is not set already.
      if (strpos($address, '@' . $site_mail_domain) === FALSE) {
        $message_from_addresses[$index] = $site_mail_address;
        if (!$reply_to) {
          $reply_to = $address;
        }
      }
    }
    $message_from_addresses = array_unique($message_from_addresses);
    $message['from'] = $message['headers']['From'] = implode(',', $message_from_addresses);

    // Additionally set a site reply-to.
    //
    // Only set reply-to to the site reply-to if we need to.
    // We only need to actually set the reply-to when 2 conditions are met:
    //
    // 1. the from address is the site mail address (variable site_mail), and
    // 2. a site replyto address is set (variable site_replyto_mail)
    //
    // The other cases are fine, e.g. if a custom@mail.domain.com address was
    // set as From address, we want to preserve it. Replys should go to this
    // address.
    if (!$reply_to && $site_reply_to && strpos($message['from'], $site_mail_address) !== FALSE) {
      $reply_to = $site_reply_to;
    }

    // If the replyto is set, use it.
    //
    // No need to check the domain of the reply to address, everything is
    // allowed here.
    if ($reply_to) {
      $message['headers']['Reply-To'] = $reply_to;
    }
  }

  // the Drupal default is to use the messages 'From' address
  // we want to be able to specify a specific bounce address
  // this header will be extracted by the mail engine and used for the `-f`
  // parameter of the `sendmail_path` command
  if (empty($message['headers']['Return-Path']) || strpos($message['headers']['Return-Path'], '@' . $site_mail_domain) === FALSE) {
    // set a default Return-Path if none is set or it is invalid
    $message['headers']['Return-Path'] = $site_return_path;
  }
  if (strpos($message['headers']['Return-Path'], '@' . $site_mail_domain) === FALSE) {
    // if the Return-Path is still invalid --> delete it
    unset($message['headers']['Return-Path']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Implements hook_form_system_site_information_settings_alter().
 *
 * Add a system settings entry to configure an email ReplyTo value
 */
function email_check_form_system_site_information_settings_alter(&$form, &$form_state) {
  form_load_include($form_state, 'php', 'email_check', 'email_check.admin');
  _email_check_system_site_information_settings_alter($form, $form_state);
}
